// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"MVMota","status":true,"description":"","parameters":{}},
{"name":"MVMotaItems","status":true,"description":"","parameters":{}},
{"name":"MVMotaMonsters","status":true,"description":"","parameters":{}},
{"name":"MVMotaAtcTypes","status":true,"description":"","parameters":{}},
{"name":"MVMotaDefTypes","status":true,"description":"","parameters":{}}
];
